name: Java CI with Gradle

on:
  push:
    branches: master
  pull_request:
    branches: date-feature-branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/wrapper-validation-action@v1
      with:
        arguments: build
